sonar.projectKey=marh08192003_Portfolio
sonar.organization=marh08192003

# Nombre y versión en la interfaz de SonarQube
sonar.projectName=Portfolio
sonar.projectVersion=1.0

# Analizar solo el código de desarrollo dentro de src
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Excluir reportes de rendimiento locales y artefactos del análisis
sonar.exclusions=node_modules/**, dist/**, .astro/**, public/**, *.html, eslint.config.js, astro.config.mjs

# Desactivar la validación estática estricta del compilador de TS para evitar que busque dependencias externas inexistentes
sonar.typescript.tsconfigPath=tsconfig.json